changelog:
  exclude:
    labels:
      - changelog-ignore
  categories:
    - title: Breaking Changes
      labels:
        - changelog-breaking
    - title: New Features
      labels:
        - changelog-enhancement
    - title: Bug Fixes
      labels:
        - bug
    - title: Other Changes
      labels:
        - "*"
