version: 2
build:
  os: ubuntu-22.04
  tools:
    python: mambaforge-22.9

sphinx:
  configuration: doc/source/conf.py
python:
  install:
  - method: setuptools
    path: .
conda:
  environment: environment.yml
formats: []
