site_name: Ecoscope Platform SDK
site_url: https://ecoscope.io/platform-sdk/
docs_dir: content
custom_dir: overrides

repo_url: https://github.com/wildlife-dynamics/ecoscope
repo_name: wildlife-dynamics/ecoscope

theme:
  name: material
  favicon: assets/ecoscope-favicon.ico
  icon:
    logo: octicons/book-24
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - announce.dismiss
    - content.code.copy
    - navigation.sections

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [../../]
          options:
            show_source: true
            show_root_heading: true
            members_order: source

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html
  - toc:
      permalink: true

extra_css:
  - stylesheets/extra.css

nav:
  - Home: index.md
  - Reference:
    - annotations: reference/annotations.md
    - connections: reference/connections.md
    - indexes: reference/indexes.md
    - jsonschema: reference/jsonschema.md
    - mock_loaders: reference/mock_loaders.md
    - schemas: reference/schemas.md
    - serde: reference/serde.md
    - tasks:
      - analysis: reference/tasks/analysis.md
      - config: reference/tasks/config.md
      - filter: reference/tasks/filter.md
      - groupby: reference/tasks/groupby.md
      - io: reference/tasks/io.md
      - preprocessing: reference/tasks/preprocessing.md
      - results: reference/tasks/results.md
      - skip: reference/tasks/skip.md
      - test: reference/tasks/test.md
      - transformation: reference/tasks/transformation.md
      - warning: reference/tasks/warning.md
