site_name: Ecoscope Platform SDK
site_url: https://ecoscope.io/platform-sdk/
docs_dir: content
custom_dir: overrides

repo_url: https://github.com/wildlife-dynamics/ecoscope
repo_name: wildlife-dynamics/ecoscope

theme:
  name: material
  favicon: assets/ecoscope-favicon.ico
  icon:
    logo: octicons/book-24
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - announce.dismiss
    - content.code.copy
    - navigation.sections

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [../../]
          options:
            show_source: true
            show_root_heading: true
            members_order: source

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html
  - toc:
      permalink: true

extra_css:
  - stylesheets/extra.css

nav:
  - Home: index.md
  - API Reference:
    - reference/index.md
    - ecoscope.platform: reference/platform.md
    - Tasks:
      - Analysis: reference/tasks/analysis.md
      - Config: reference/tasks/config.md
      - Filter: reference/tasks/filter.md
      - GroupBy: reference/tasks/groupby.md
      - IO: reference/tasks/io.md
      - Preprocessing: reference/tasks/preprocessing.md
      - Results: reference/tasks/results.md
      - Skip: reference/tasks/skip.md
      - Test: reference/tasks/test.md
      - Transformation: reference/tasks/transformation.md
      - Warning: reference/tasks/warning.md
