site_name: Ecoscope Platform SDK
site_url: https://ecoscope.io/platform-sdk/
docs_dir: content
custom_dir: overrides

repo_url: https://github.com/wildlife-dynamics/ecoscope
repo_name: wildlife-dynamics/ecoscope

theme:
  name: material
  favicon: assets/ecoscope-favicon.ico
  icon:
    logo: octicons/book-24
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - announce.dismiss
    - content.code.copy
    - navigation.sections

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [../../]
          options:
            show_source: true
            show_root_heading: true
            show_root_full_path: true
            members_order: alphabetical
            show_if_no_docstring: true
            show_signature_annotations: true
            show_labels: true
            group_by_category: true
            show_category_heading: true
            merge_init_into_class: true
            show_bases: true
            docstring_style: google
            filters:
              - "!^_"

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html
  - toc:
      permalink: true

extra_css:
  - stylesheets/extra.css

nav:
  - Home: index.md
  - Concepts: concepts.md
  - Getting Started: getting-started.md
  - Understanding spec.yaml: understanding-spec.md
  - Built-in Tasks: built-in-tasks.md
  - Examples: examples.md
  - Troubleshooting: troubleshooting.md
  - Tutorials:
    - Tutorials Overview: tutorials.md
    - Your First Custom Task: tutorials/first-custom-task.md
    - Data Sources: tutorials/data-sources.md
    - Widgets: tutorials/widgets.md
    - Groupers: tutorials/groupers.md
    - Form Customization: tutorials/form-customization.md
  - Reference:
    - Tasks:
      - io: reference/tasks/io.md
      - filter: reference/tasks/filter.md
      - preprocessing: reference/tasks/preprocessing.md
      - transformation: reference/tasks/transformation.md
      - groupby: reference/tasks/groupby.md
      - analysis: reference/tasks/analysis.md
      - results: reference/tasks/results.md
      - config: reference/tasks/config.md
      - skip: reference/tasks/skip.md
      - warning: reference/tasks/warning.md
      - test: reference/tasks/test.md
    - schemas: reference/schemas.md
    - connections: reference/connections.md
    - indexes: reference/indexes.md
    - annotations: reference/annotations.md
    - Advanced:
      - jsonschema: reference/jsonschema.md
      - mock_loaders: reference/mock_loaders.md
