name: Lint

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "*" ]
    
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install pre-commit and mypy
        run: python -m pip install pre-commit mypy
      - name: Install ecoscope
        run: python -m pip install ".[all]"
      - name: Lint
        run: |
          pre-commit install
          pre-commit run --all-files
      - name: Mypy
        run: |
          mypy ecoscope