name: Lint

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "*" ]
    
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install pre-commit
        run: pip install pre-commit
      - name: Lint
        run: |
          pre-commit install
          pre-commit run --all-files