name: Wizard Tests

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["**"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.actor }}
  cancel-in-progress: true

jobs:
  Wizard:
    name: wizard
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -leo pipefail {0}

    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version: "3.12"
      - name: Install wizard providers
        env:
          SETUPTOOLS_SCM_PRETEND_VERSION: "0.0.0"
        run: |
          python -m ensurepip --upgrade
          pip install -e "./wizard/ecoscope-wizard-providers[dev]"
      - name: Test wizard providers
        working-directory: wizard/ecoscope-wizard-providers
        run: pytest -v --color=yes
